---
language: ruby
bundler_args: --without development system_tests
before_install:
  - rm gemfiles/Gemfile.lock || true
  - rm gemfiles/Gemfile.ruby1.9.3.lock || true
  - gem update --system
script: 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.ruby1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes CHECK=test
  - rvm: 2.1.9
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.1.9
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.2.6
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.3
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.3.3
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=rubocop
  - rvm: 2.5.1
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=test
  - rvm: 2.5.1
    gemfile: gemfiles/Gemfile
    env: PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes CHECK=rubocop
